name: Deploy via SSH

on:
  push:
    branches:
      - main

env:
  SERVER_HOST: access935892104.webspace-data.io
  SERVER_USER: u109668880

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build code
      run: |
        # Add your build commands here

    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: whoami
        
    - name: Deploy via SSH
      env:
        DEPLOY_DIR: /portfolio
      run:
        rsync -avz --delete build/ ${DEPLOY_DIR}
        ssh ${{ env.SERVER_USER }}@${{ env.SERVER_HOST }} 'cd ${DEPLOY_DIR}'
