name: Deploy via SSH

on:
  push:
    branches:
      - main

env:
  SERVER_HOST: access935892104.webspace-data.io
  SERVER_USER: u109668880
  SERVER_PASSWORD: Songoku10!

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Connect via SSH
      run: sshpass -p ${{ env.SERVER_PASSWORD }} ssh ${{ env.SERVER_USER }}@${{ env.SERVER_HOST }}

    - name: Deploy via SSH
      run: rsync -avz . ${{ env.SERVER_USER }}@${{ env.SERVER_HOST }}:/portfolio
